networks:
  dev:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
      - REDIS_URL=redis://redis:6379/0
    networks:
      - dev
    depends_on:
      - db
      - redis
    expose:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    networks:
      - dev
    depends_on:
      - backend
    ports:
      - "5173:5173"
  
  db:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= password
      - POSTGRES_DB= mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432"
    
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    container_name: ngninx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - dev
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  