"""create_tables2

Revision ID: ace7c49c6150
Revises: c0431fcc2f13
Create Date: 2025-10-25 04:39:14.543852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ace7c49c6150'
down_revision: Union[str, Sequence[str], None] = 'c0431fcc2f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('rooms', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rooms', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
